// bertui/src/utils/env.js - COMPLETE FIXED VERSION
import { join } from 'path';
import { existsSync, readFileSync } from 'fs';
import logger from '../logger/logger.js';

/**
 * Load environment variables from .env file
 * @param {string} root - Project root directory
 * @returns {Object} Environment variables
 */
export function loadEnvVariables(root) {
  const envPath = join(root, '.env');
  const envVars = {};
  
  if (existsSync(envPath)) {
    try {
      // ✅ FIXED: Use Node.js readFileSync instead of Bun.file().text()
      const envContent = readFileSync(envPath, 'utf-8');
      const lines = envContent.split('\n');
      
      for (const line of lines) {
        // Skip empty lines and comments
        if (!line.trim() || line.trim().startsWith('#')) continue;
        
        // Parse KEY=VALUE
        const match = line.match(/^([^=]+)=(.*)$/);
        if (match) {
          const key = match[1].trim();
          let value = match[2].trim();
          
          // Remove quotes if present
          if ((value.startsWith('"') && value.endsWith('"')) ||
              (value.startsWith("'") && value.endsWith("'"))) {
            value = value.slice(1, -1);
          }
          
          envVars[key] = value;
        }
      }
      
      if (Object.keys(envVars).length > 0) {
        logger.debug(`Loaded ${Object.keys(envVars).length} environment variables from .env`);
      }
    } catch (error) {
      logger.warn(`Failed to load .env: ${error.message}`);
    }
  }
  
  return envVars;
}

/**
 * Generate JavaScript code to expose environment variables
 * @param {Object} envVars - Environment variables object
 * @returns {string} JavaScript code
 */
export function generateEnvCode(envVars) {
  const exports = Object.entries(envVars)
    .map(([key, value]) => `export const ${key} = ${JSON.stringify(value)};`)
    .join('\n');
  
  return `// Auto-generated environment variables
// Do not edit this file manually

${exports}

// Access via: import { VAR_NAME } from './env.js'
`;
}

/**
 * Replace process.env references in code
 * @param {string} code - Source code
 * @param {Object} envVars - Environment variables
 * @returns {string} Code with replaced env vars
 */
export function replaceEnvInCode(code, envVars) {
  let modified = code;
  
  for (const [key, value] of Object.entries(envVars)) {
    // Replace process.env.KEY with actual value
    const regex = new RegExp(`process\\.env\\.${key}\\b`, 'g');
    modified = modified.replace(regex, JSON.stringify(value));
  }
  
  return modified;
}